spring:
    datasource:
        password: 12345
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    jwt:
        secret_key: java-10
server:
    port: 8080
